#pragma config(Sensor, S3,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "conf.txt"

void printOnScreen() {

	int value = SensorValue[sonar];
	nxtDisplayString(1, "Sonar : %d", value);

	wait1Msec(50);
}

void logSensorData() {
	int i=0;

	for(i=0; i<10; i++) {
		AddToDatalog(0, SensorValue[sonar]);
	}

	//nxtDisplayTextLine(3, "Data collected");
	//wait1Msec(50);
}

task main()
{

	int i = 0;
	//print on screen and in the data log
	while(1) {
		printOnScreen();
		//logSensorData();
	}

	//nxtDisplayString(3,"%f",SensorValue[sonar]);
	//wait1Msec(50000);
	SaveNxtDatalog();

}
